services:
  api:
    build: .
    container_name: iris-api
    ports:
      - "8000:8000"
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5001
      - MODEL_URI=models:/iris_model/latest
      - MLFLOW_S3_ENDPOINT_URL=http://minio:9000
      - AWS_ACCESS_KEY_ID=minioadmin
      - AWS_SECRET_ACCESS_KEY=minioadmin
    healthcheck:
      test: ["CMD", "python", "-c",
             "import urllib.request,sys; sys.exit(0 if urllib.request.urlopen('http://localhost:8000/health').status==200 else 1)"]
      interval: 10s
      timeout: 3s
      retries: 5
    depends_on:
      - mlflow

  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - ./minio_data:/data
    command: server /data --console-address ":9001"

  minio-create-bucket:
    image: minio/mc:latest
    container_name: minio-create-bucket
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set myminio http://minio:9000 minioadmin minioadmin;
      /usr/bin/mc mb myminio/mlflow --ignore-existing;
      /usr/bin/mc anonymous set download myminio/mlflow;
      exit 0;
      "

  mlflow:
    image: python:3.11-slim
    container_name: mlflow
    ports:
      - "5001:5001"
    environment:
      - MLFLOW_S3_ENDPOINT_URL=http://minio:9000
      - AWS_ACCESS_KEY_ID=minioadmin
      - AWS_SECRET_ACCESS_KEY=minioadmin
    volumes:
      - ./mlflow_data:/mlflow_data
    command: bash -c "pip install mlflow==2.13.0 boto3 && mlflow server --host 0.0.0.0 --port 5001 --backend-store-uri sqlite:////mlflow_data/mlflow.db --default-artifact-root s3://mlflow/"
    depends_on:
      - minio-create-bucket

  airflow:
    image: apache/airflow:2.9.2-python3.11
    container_name: airflow
    environment:
      - _AIRFLOW_DB_MIGRATE=true
      - _AIRFLOW_WWW_USER_CREATE=true
      - _AIRFLOW_WWW_USER_USERNAME=admin
      - _AIRFLOW_WWW_USER_PASSWORD=admin
      - _PIP_ADDITIONAL_REQUIREMENTS=--no-cache-dir scikit-learn pandas mlflow==2.13.0 joblib boto3
      - MLFLOW_S3_ENDPOINT_URL=http://minio:9000
      - AWS_ACCESS_KEY_ID=minioadmin
      - AWS_SECRET_ACCESS_KEY=minioadmin
    ports:
      - "8080:8080"
    volumes:
      - ./dags:/opt/airflow/dags
      - .:/opt/airflow/lab4
      - ./mlflow_data:/mlflow_data
    command: standalone
    depends_on:
      - mlflow

  prometheus:
    image: prom/prometheus:v2.53.0
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - api

  grafana:
    image: grafana/grafana:11.1.0
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - prometheus
